"""preprocess package

Lightweight text preprocessing helpers.

Exports a few convenience functions from `text_preprocess`.
"""

from .text_preprocess import (
    strip_html,
    to_lowercase,
    normalize_whitespace,
    remove_urls,
    simple_tokenize,
    clean_text,
    word_count,
    character_count,
    average_word_length,
    stopwords_in_text,
    stopword_count,
    count_hashtags_and_mentions,
    has_digits,
    uppercase_word_count,
    expand_contractions,
    count_emails,
    remove_emails,
    count_and_remove_emails,
    count_urls,
    count_and_remove_urls,
    remove_retweets,
    remove_html_tags,
    to_ascii,
    remove_special_characters,
    squeeze_repeated_chars,
    remove_stopwords,
    to_base_form,
    remove_common_words,
    remove_rare_words,
    correct_spelling,
    noun_chunks_and_phrases,
    ngrams,
    bigrams,
    singularize_words,
    pluralize_words,
    naive_bayes_sentiment,
    detect_language,
    translate_text,
    lemmatize,
)

__all__ = [
    "strip_html",
    "to_lowercase",
    "normalize_whitespace",
    "remove_urls",
    "simple_tokenize",
    "clean_text",
    "word_count",
    "character_count",
    "average_word_length",
    "stopwords_in_text",
    "stopword_count",
    "count_hashtags_and_mentions",
    "has_digits",
    "uppercase_word_count",
    "expand_contractions",
    "count_emails",
    "remove_emails",
    "count_and_remove_emails",
    "count_urls",
    "count_and_remove_urls",
    "remove_retweets",
    "remove_html_tags",
    "to_ascii",
    "remove_special_characters",
    "squeeze_repeated_chars",
    "remove_stopwords",
    "to_base_form",
    "remove_common_words",
    "remove_rare_words",
    "correct_spelling",
    "noun_chunks_and_phrases",
    "ngrams",
    "bigrams",
    "singularize_words",
    "pluralize_words",
    "naive_bayes_sentiment",
    "detect_language",
    "translate_text",
    "lemmatize",
]

__version__ = "0.1.0"
